# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ajuda_db
      POSTGRES_USER: ajuda
      POSTGRES_PASSWORD: ajuda
    ports:
      - 5432:5432